@extends('errors.layout')
@section('title', 'Page not found')
@section('code', '404')
@section('heading', 'Page not found')
@section('message', 'The page you requested is not available. Please return to the school website or contact the office.')
