@extends('errors.layout')
@section('title', 'Service unavailable')
@section('code', '500')
@section('heading', 'Something needs attention')
@section('message', 'The school website could not complete this request. Please try again in a moment or contact the office.')
